language: groovy
jdk:
  - oraclejdk7
script: ./grailsw refresh-dependencies && ./grailsw clean && ./grailsw "test-app unit:" && cd test/apps/shopping-list && ./grailsw refresh-dependencies && ./grailsw clean && ./grailsw "test-app functional:"